#!/bin/bash
# -*- coding: utf-8 -*-
# -*- encoding: utf-8 -*-
#
# Copyright (c) 2023 anqi.huang@outlook.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function gs_init_vim() {
    local gs_conf_dir=$HOME/bin/global_scripts/conf
    # check if the gs conf dir exists
    if [ ! -d ${gs_conf_dir} ]; then
        mkdir -p ${gs_conf_dir}
    fi

    local gs_conf_vim_dir=$HOME/bin/global_scripts/conf/gs_vim

    if [ "${_GS_CONFIG_PATH}/gs_vim" = "$gs_conf_dir/gs_vim" ]; then
        echo "don't need cp"
    else
        rm -rf $gs_conf_dir/gs_vim
        cp -r ${_GS_CONFIG_PATH}/gs_vim $gs_conf_vim_dir
    fi

    mv $gs_conf_vim_dir/.vimrc $HOME/.vimrc
    source $HOME/.vimrc
}