#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -*- encoding: utf-8 -*-
#
# Copyright (c) 2023 anqi.huang@outlook.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import os
import subprocess


def file_exists(file):
    exists = os.path.isfile(file) and os.path.exists(file)
    return exists


def dir_exists(file):
    exists = os.path.isdir(file) and os.path.exists(file)
    return exists


def main():
    gs_config_path = os.getenv("_GS_CONFIG_PATH")
    if gs_config_path is None or dir_exists(gs_config_path) is False:
        gs_config_path = os.path.join(os.getenv("HOME"), "code/github/global_scripts/conf")
    else:
        print(gs_config_path)

    gs_config_cargo = os.path.join(gs_config_path, "cargo/config")
    if file_exists(gs_config_cargo) is False:
        print("{} don't exists")
        return 0

    if file_exists(gs_config_cargo):
        home = os.getenv("HOME")
        dest = os.path.join(home, ".cargo/config")
        cmd = "cp {} {}".format(gs_config_cargo, dest)

        # print(cmd)
        ret, output = subprocess.getstatusoutput(cmd)
        if ret != 0:
            print("cp cargo config error, ", output)

    return 1


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        exit()
